# Site settings
title: Hercules Industries Blog
email: vinko.grgic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A blog about the cyborg future.
url: "http://herculesindustries.co" # the base hostname & protocol for your site
github_username:  vinkogrgic

# Build settings
markdown: kramdown
