# Site settings
title: Hercules Industries Blog
email: vinko.grgic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about the cyborg future.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://herculesindustries.co" # the base hostname & protocol for your site
github_username:  vinkogrgic

# Build settings
markdown: kramdown
